### ISSUE TITLE
It is possible to add a phone number that is 9 digits long

### ISSUE THREAD

**Issue by SamuelFoo** [AY2425S1-CS2103T-T15-4/tp#149]
![image](https://github.com/user-attachments/assets/be7ec3f7-332a-4ec1-a59f-22d2ae1f1ed0)

**Comment by LeeZeHao** [comment]
This is not a constraint we should add, based on this:
![image](https://github.com/user-attachments/assets/6e05590b-17aa-48f1-b192-878c263f5a3a)
