### ISSUE TITLE
[PE-D][Tester C] Not every character is allowed for address.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T15-4/tp#213]
My address is: John street, block 123, #01-01, n/alibaba suqare

However I am unable to add the employee inside:
![Screenshot 2024-11-08 at 4.26.17 PM.png](https://raw.githubusercontent.com/calebyyy/ped/main/files/bfbc6155-e9f7-4f1a-9b3f-4a40518c2d74.png)

Steps to reproduce:
type this command:  add id/1110011 n/zwe p/91165432 e/johnd@example.com a/John street, block 123, #01-01, n/alibaba square
Expected: System message noting success and details of employee edited
Actual: Multiple values specified for the following single-valued field(s): n/

I was told per the UG ANY characters are allowed as shown below:

![Screenshot 2024-11-08 at 4.28.04 PM.png](https://raw.githubusercontent.com/calebyyy/ped/main/files/f24ef4d8-461f-4949-ade1-3316e47b7994.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: calebyyy/ped#3

**Comment by LeeZeHao** [comment]
This should be fixed by the PR #280
