### ISSUE TITLE
[PE-D][Tester C] App does not work for long character names

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T15-4/tp#250]
Entire app hangs when having long names.

Steps to reproduce: 
'''
add id/1 n/{$name} p/98765432 e/johnd@example.com a/John street, block 123,
#01-01
''''
where {$name} is "lol" repeated 2 million times

Expected output: Application works as intended
Actual: App cannot be used 
![Screenshot 2024-11-08 at 5.20.42 PM.png](https://raw.githubusercontent.com/calebyyy/ped/main/files/8aaeeaa8-3ee0-4ac5-9239-bc9808c2c123.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: calebyyy/ped#10

**Comment by LeeZeHao** [comment]
This counts as deliberate sabotage and is not a bug that needs to be fixed.
Our app does handle long names properly:
![image](https://github.com/user-attachments/assets/c7de39ef-f44f-4162-9338-50f3e10bc111)
