### ISSUE TITLE
[PE-D][Tester E] Handling Maximum Integer values

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T15-4/tp#263]
![Screenshot 2024-11-08 at 20.12.33.png](https://raw.githubusercontent.com/nihalramesh12629/ped/main/files/d4e15fab-63ae-4c19-8a88-ab8c4648184f.png)

When large integer values are input, the application is not able to handle it, and it shows the error `ID should only contain numeric characters` in the result box, which is not exactly a fitting description of the error at hand.

Perhaps, the application should indicate what the maximum value it can take, and display an error accordingly to show if the maximum integer value has been exceeded.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: nihalramesh12629/ped#6

**Comment by Professional-Procrastinat0r** [comment]
![image](https://github.com/user-attachments/assets/0bab7c23-6b8e-45b1-a300-06ec6ea07aa5)
 Can be considered extreme user behaviour
