### ISSUE TITLE
[PE-D][Tester E] Mass clearing of all assignments

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T15-4/tp#271]
As a HR associate, one of the possible features I could benefit from is clearing all the assignments at once, which is currently not possible. Perhaps that could have been one of the features added. 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: nihalramesh12629/ped#10

**Comment by LeeZeHao** [comment]
We should just put this under planned enhancements, or something
